name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Configure Nix experimental features
        run: |
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

      - name: Enable Cachix cache for devenv
        uses: cachix/cachix-action@v16
        with:
          name: devenv

      - name: Install devenv CLI
        run: |
          nix profile install nixpkgs#devenv

      - name: Build dev shell and run tests with devenv
        env:
          CI: true
        run: |
          export PATH="$HOME/.nix-profile/bin:$PATH"
          # Build the dev shell and run devenv test inside it. --no-pure-eval allows devenv to detect project path.
          nix --extra-experimental-features 'nix-command flakes' develop --no-pure-eval --command devenv test

      - name: Show environment (debug)
        if: always()
        run: |
          which devenv || true
          devenv --version || true
          nix --version || true