name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - url: https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.tar.gz
          - url: https://github.com/neovim/neovim/releases/download/v0.11.0/nvim-linux-x86_64.tar.gz

    steps:
      - uses: actions/checkout@v4

      - name: Setup Neovim
        run: |
          mkdir -p _neovim
          curl -sL ${{ matrix.url }} | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          ln -s $(pwd) ~/.local/share/nvim/site/pack/vendor/start

      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --version
          make test